/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zyj.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.zyj.domain.Message;
import com.zyj.domain.Users;
import com.zyj.service.imp.MessageServiceImp;
import com.zyj.service.inter.MessageServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 01-16-2018
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class GoMessageUiAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		MessageServiceInter msi = new MessageServiceImp();
		Users user = (Users) request.getSession().getAttribute("userInfo");
		List<Message> messages = msi.showMessage(user);
		request.getSession().setAttribute("messageInfo", messages);
		return mapping.findForward("goMessageUi");
	}
}