/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zyj.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.zyj.domain.Message;
import com.zyj.domain.Users;
import com.zyj.service.imp.UserServiceImp;
import com.zyj.service.inter.UserServiceInter;
import com.zyj.struts.form.MessageForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-17-2018
 * 
 * XDoclet definition:
 * @struts.action parameter="flage"
 */
public class GoPublishMessageUiAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward goPublishMessage(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goPublishMessageUi");
	}
	
	public ActionForward PublishMessage(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		
		MessageForm messageForm = (MessageForm) form;
		
		Message message = new Message();
	
		UserServiceInter userServiceInter = new UserServiceImp();
		
		message.setGetter(userServiceInter.findUsersByName(messageForm.getGetter()));
		message.setSender((Users)request.getSession().getAttribute("userInfo"));
		message.setContent(messageForm.getContent());
		message.setMesTime(new Date());
		
		userServiceInter.save(message);
		
		return mapping.findForward("ok");
	}
}