/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zyj.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.zyj.domain.Users;
import com.zyj.service.imp.UserServiceImp;
import com.zyj.service.inter.UserServiceInter;
import com.zyj.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-16-2018
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		UserForm userForm = (UserForm)form;
		
		Users user = new Users();
		user.setUserid(Integer.parseInt(userForm.getUserid()));
		user.setPasswd(userForm.getPasswd());
		
		UserServiceInter  userServiceInter  = new UserServiceImp();
		
		user = userServiceInter.checkUsers(user);
	
		if(user != null) {
			request.getSession().setAttribute("userInfo", user);
			return mapping.findForward("loginok");
		}else{
			return mapping.findForward("goLoginUi");
		}
		
	}
	
	public ActionForward logout(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		request.getSession().invalidate();
		return mapping.findForward("goLoginUi");
	}
}